import { Inter } from 'next/font/google'
import '../../globals.css'

// Using Inter for a cleaner, more modern look that matches the target design
const inter = Inter({ subsets: ['latin'], weight: ['400', '500', '700'] })

export const metadata = {
  title: 'My Profile', // You can update this
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* This <main> tag will center all its children on the page */}
        <main className="flex items-center justify-center min-h-screen p-4">
          {children}
        </main>
      </body>
    </html>
  )
}